apiVersion: v1
entries:
  paperless-ngx:
  - apiVersion: v2
    appVersion: 2.19.4
    created: "2025-11-11T15:48:12.266185942Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://docker.io/bitnamicharts
      version: ^16.5.6
    - condition: valkey.internal
      name: valkey
      repository: https://valkey.io/valkey-helm/
      version: 0.7.7
    description: A document management system that transforms your physical documents
      into a searchable online archive so you can keep, well, less paper.
    digest: 4a84103b8ce4ebf6f4d0d855c7f7bf458500ea610801e6ad05546a285e6711b5
    home: https://wrenix.eu/docs/helm-charts/paperless-ngx/
    icon: https://github.com/paperless-ngx/paperless-ngx/raw/main/resources/logo/web/svg/square.svg
    keywords:
    - paperless
    - paperless-ng
    - paperless-ngx
    - dms
    - document
    maintainers:
    - name: WrenIX
      url: https://wrenix.eu
    name: paperless-ngx
    sources:
    - https://github.com/paperless-ngx/paperless-ngx
    - https://git.chaos.fyi/wrenix/helm-charts/src/branch/main/paperless-ngx
    - https://codeberg.org/wrenix/helm-charts/src/branch/main/paperless-ngx
    type: application
    urls:
    - https://example.com/paperless-ngx-0.3.2.tgz
    version: 0.3.2
generated: "2025-11-11T15:48:12.257107078Z"
